# Generated by Django 4.2.8 on 2024-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ethereum_address",
            field=models.CharField(default="jifejoifj", max_length=42),
        ),
        migrations.AddField(
            model_name="customuser",
            name="private_key",
            field=models.CharField(default="djhfvoje", max_length=66),
        ),
    ]
